### ISSUE TITLE
Language Agnostic Multilingual Information Retrieval with Contrastive Learning

### ISSUE THREAD

**Issue by sendRainAutumn** [xiyanghu/multilingualIR#1]
Hello, when will the code be released?

**Comment by xiyanghu** [comment]
The code will be released after Amazon's legal team approves its public release.

The code implementation is based on [DPR](https://github.com/facebookresearch/DPR) and [CCP](https://github.com/wuning0929/CCP_IJCAI22). You may want to check out them at this moment.

**Comment by sendRainAutumn** [comment]
Thanks!
